name: PR Verify

on:
  pull_request:
    branches: [main]
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
      - ready_for_review

  merge_group:
    types: [checks_requested]

jobs:
  odd-number-check:
    runs-on: ubuntu-latest
    steps:
      - name: Generate random number and test odd/even
        run: |
          num=$(( RANDOM % 100 ))
          echo "Number is $num"
          if (( num % 2 == 0 )); then
            echo "Even → FAIL"
            echo "Faking passing because we know that this bit works correctly as a trigger"
            exit 0
          else
            echo "Odd → PASS"
            exit 0
          fi
  check-path:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Detect relevant changes
        uses: dorny/paths-filter@v3
        id: relevant-changes
        with:
          base: "main"
          ref: ${{ github.ref }}
          filters: |
            allowed:
              - 'thisCanChange/**'  # Only run if files in this path are changed
      - name: Debug filter output here
        run: |
          echo "steps.relevant-changes.outputs.allowed = ${{ steps.relevant-changes.outputs.allowed }}"
          echo "show outputs: ${{ toJson(steps.relevant-changes.outputs) }}"
      - name: Allowed echo
        if: ${{ steps.relevant-changes.outputs.allowed == true }}
        run: echo "✅ Changes detected in thisCanChange/** — running downstream steps"
      - name: Not Allowed echo
        if: ${{ steps.relevant-changes.outputs.allowed == false }}
        run: echo "🚨 Changes not detected in thisCanChange/** — running downstream steps"
